"""
Failing-first SHARED CONTRACT test for the outbound `target-writer` port of the CLAUDART law
engine (SPEC D15 / P2.3). Neither the port module nor any adapter exists yet — this file is
expected to fail on IMPORT (ImportError), and that failure IS the deliverable (observed RED, per
`.claude/scripts/law/SCHEMA.md`, `.claude/scripts/law/LESSONS.md`, `graph-development.md` §4-5,
and `evidence-gauntlet.md`).

============================================================================
API CONTRACT — the implementer builds exactly this shape (chosen by this test file)
============================================================================

Package layout: `.claude/scripts/law/ports/target_writer.py` (the Protocol + the marker constants
+ the reference implementation below) and one module per adapter, e.g.
`.claude/scripts/law/adapters/claude_md_target.py` (class `ClaudeMdTargetWriter`, node
`adapter/claude-md-target`). The port's methods are INSTANCE methods (not free functions) so that
an adapter is a constructible object with no required constructor arguments —
`ClaudeMdTargetWriter()` must work with zero args, discovering its target purely from the `path`
argument passed to each call, mirroring `RecordStore`'s precedent
(`.claude/scripts/law/ports/record_store.py`).

    # law/ports/target_writer.py
    from typing import Protocol

    BEGIN_MARKER = "<!-- laws:begin — generated by claudart-law.sh compile; edit frontmatter, not this block -->"
    END_MARKER = "<!-- laws:end -->"

    class TargetWriter(Protocol):
        def read(self, path: str) -> str:
            # Returns the full raw content of the file at `path`, verbatim, decoded as UTF-8.
            ...

        def check(self, path: str, block: str) -> tuple[bool, str]:
            # Reads the file at `path`, locates the CURRENT text between the markers (see the
            # marker-matching rule below; raises ValueError per that rule if the markers cannot
            # be located), and compares it to `block`.
            # Returns (zero_diff, diff):
            #   - zero_diff is True and diff is "" (falsy) when the current between-markers text
            #     is exactly `block`.
            #   - zero_diff is False and diff is a non-empty UNIFIED DIFF (difflib.unified_diff
            #     style: "---"/"+++" header lines, "@@" hunk headers, "-"/"+" changed lines)
            #     naming what differs, when it is not.
            # `check` NEVER writes to `path` under any outcome — this is load-bearing: a caller
            # uses `check` to decide WHETHER to call `replace_block`, and a `check` that mutates
            # the file defeats that purpose.
            ...

        def replace_block(self, path: str, block: str) -> None:
            # Rewrites the file at `path` so that the text between the markers becomes exactly
            # `block`. Everything before the begin marker's line (inclusive of that line) and
            # everything from the end marker's line (inclusive of that line) onward is preserved
            # byte-for-byte — including blank lines and the file's trailing newline (or lack of
            # one). The markers themselves are never altered. Calling `replace_block` with the
            # block that is already there produces a byte-identical file (a true no-op, not
            # merely an equivalent rewrite).
            # Raises ValueError, and leaves the file byte-for-byte UNCHANGED, when the markers
            # cannot be located per the marker-matching rule below (missing either marker, or
            # the end marker appearing at or before the begin marker).
            ...

============================================================================
MARKER-MATCHING RULE (this test file's choice — the next node must implement exactly this)
============================================================================

The begin marker is matched by its `<!-- laws:begin` PREFIX only: the FIRST line in the file
whose stripped text starts with that literal prefix. The text after the prefix (the em dash and
comment) is NOT load-bearing — a bare `<!-- laws:begin -->` line matches equally.

The end marker is matched by an EXACT line match on `<!-- laws:end -->`, taken as the LAST such
line in the whole file, provided it appears strictly after the located begin-marker line
(otherwise: not found / wrong order → raise). Taking the end marker as the RIGHTMOST match, not
the first one after the begin marker, is deliberate: it is what lets a `block` argument itself
contain marker-look-alike text (e.g. prose that quotes the marker literally) without that
embedded text being mistaken for the true end marker on a later `read`/`check`/`replace_block`
call — the real structural end marker is always the last one in the document. A `block` is
written completely verbatim; this port never re-scans or rejects the text it is given.

Exception type for every contract violation in this file (missing marker, wrong order): the
sibling `record-store` port's precedent — a plain `ValueError`.

============================================================================
REFERENCE IMPLEMENTATION — `InMemoryTargetWriter` (ships with port/target-writer, P2.3)
============================================================================

Per `graph-development.md` §4 ("the port task ships its own fake so consumers can proceed") and
`RecordStore`'s precedent (`InMemoryRecordStore`): despite the name, it performs real file I/O —
every method discovers its target purely from the `path` argument, holding no additional
in-process state. It is what lets this shared suite be green at the port node, before
`adapter/claude-md-target` exists, without the fail-open of collecting zero tests.

============================================================================
EXTENDING THIS CONTRACT — the one-edit instruction for the next adapter
============================================================================

`TargetWriterContract` below holds every assertion and is NOT itself a `unittest.TestCase`
subclass (so bare `unittest discover` never collects or runs it directly — only its
`*ContractTests` subclasses are collected). To add the adapter's node to this shared contract,
add ONE small subclass, e.g.:

    from law.adapters.claude_md_target import ClaudeMdTargetWriter

    class ClaudeMdTargetContractTests(TargetWriterContract, unittest.TestCase):
        def make_writer(self):
            return ClaudeMdTargetWriter()

That subclass inherits every assertion in `TargetWriterContract` unchanged — no test body is
ever copied. Do not add this import/subclass until `law.adapters.claude_md_target` actually
exists: importing a module that does not exist yet would fail this whole file on collection and
take the port's own (already-passing) reference-implementation tests down with it — exactly the
mistake `graph-development.md`'s PORT-TEST-MISSING/ADAPTER-SKIPS-PORT-TEST enforcers exist to
catch in the other direction.
============================================================================
"""

import os
import shutil
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "..", ".claude", "scripts"))

from law.ports.target_writer import (  # noqa: F401
    BEGIN_MARKER,
    END_MARKER,
    InMemoryTargetWriter,
    TargetWriter,
)


# ---------------------------------------------------------------------------
# fixtures (built inline — never read from tests/law/fixtures/)
# ---------------------------------------------------------------------------

# PREFIX ends exactly at the newline that terminates the begin-marker line; SUFFIX begins
# exactly at the end-marker line. Everything a test writes as `PREFIX + <middle> + SUFFIX`
# therefore has an unambiguous "text between the markers" — <middle> — which is what every
# assertion below reasons about.
PREFIX = (
    "See @.claude/CONTEXT.md for the current state of work.\n"
    "\n"
    "Human-authored prose stays above the block, verbatim.\n"
    "\n"
    + BEGIN_MARKER
    + "\n"
)

SUFFIX = (
    END_MARKER
    + "\n"
    "\n"
    "Human-authored prose stays below the block, verbatim.\n"
    "A second line of prose, with a trailing blank line below.\n"
    "\n"
)

OLD_MIDDLE = "old law line one\nold law line two\n"


# ---------------------------------------------------------------------------
# the shared contract — a mixin, deliberately NOT a unittest.TestCase subclass
# ---------------------------------------------------------------------------

class TargetWriterContract:
    """Every assertion the target-writer port must satisfy, for ANY adapter `make_writer()` returns.

    Subclasses must also inherit `unittest.TestCase` and implement `make_writer(self)`.
    """

    def make_writer(self):
        raise NotImplementedError("subclass must return an adapter instance")

    def setUp(self):
        self.writer = self.make_writer()
        self.tmp = tempfile.mkdtemp(prefix="target-writer-contract-")
        self.path = os.path.join(self.tmp, "CLAUDE.md")

    def tearDown(self):
        shutil.rmtree(self.tmp, ignore_errors=True)

    def _write(self, content):
        with open(self.path, "wb") as f:
            f.write(content.encode("utf-8"))

    def _read_bytes(self):
        with open(self.path, "rb") as f:
            return f.read()

    # -- 1. read() ------------------------------------------------------------

    def test_read_returns_full_file_content_verbatim(self):
        full = PREFIX + OLD_MIDDLE + SUFFIX
        self._write(full)

        self.assertEqual(self.writer.read(self.path), full)

    # -- 2. check() — identical vs differing ----------------------------------

    def test_check_identical_block_reports_zero_diff_and_empty_diff(self):
        self._write(PREFIX + OLD_MIDDLE + SUFFIX)

        zero_diff, diff = self.writer.check(self.path, OLD_MIDDLE)

        self.assertIs(zero_diff, True)
        self.assertFalse(diff)

    def test_check_differing_block_reports_unified_diff_naming_the_difference(self):
        self._write(PREFIX + "alpha line\n" + SUFFIX)

        zero_diff, diff = self.writer.check(self.path, "beta line\n")

        self.assertIs(zero_diff, False)
        self.assertTrue(diff)
        removed = [
            line for line in diff.splitlines() if line.startswith("-") and not line.startswith("---")
        ]
        added = [
            line for line in diff.splitlines() if line.startswith("+") and not line.startswith("+++")
        ]
        self.assertTrue(any("alpha line" in line for line in removed), diff)
        self.assertTrue(any("beta line" in line for line in added), diff)

    # -- 3. check() writes nothing — load-bearing -----------------------------

    def test_check_writes_nothing_when_blocks_differ(self):
        self._write(PREFIX + OLD_MIDDLE + SUFFIX)
        before = self._read_bytes()

        zero_diff, _diff = self.writer.check(self.path, "a completely different block\n")

        self.assertIs(zero_diff, False)
        self.assertEqual(self._read_bytes(), before)

    def test_check_writes_nothing_when_blocks_are_identical(self):
        self._write(PREFIX + OLD_MIDDLE + SUFFIX)
        before = self._read_bytes()

        zero_diff, _diff = self.writer.check(self.path, OLD_MIDDLE)

        self.assertIs(zero_diff, True)
        self.assertEqual(self._read_bytes(), before)

    # -- 4. replace_block() swaps only the middle -----------------------------

    def test_replace_block_swaps_only_the_middle_text(self):
        self._write(PREFIX + OLD_MIDDLE + SUFFIX)
        new_middle = "new law line one\nnew law line two\n"

        self.writer.replace_block(self.path, new_middle)

        result = self._read_bytes().decode("utf-8")
        self.assertEqual(result, PREFIX + new_middle + SUFFIX)

    def test_replace_block_markers_survive_verbatim(self):
        self._write(PREFIX + OLD_MIDDLE + SUFFIX)

        self.writer.replace_block(self.path, "new content\n")

        result = self._read_bytes().decode("utf-8")
        self.assertEqual(result.count(BEGIN_MARKER), 1)
        self.assertEqual(result.count(END_MARKER), 1)

    def test_replace_block_preserves_prefix_and_suffix_byte_identical(self):
        self._write(PREFIX + OLD_MIDDLE + SUFFIX)

        self.writer.replace_block(self.path, "replacement content\n")

        result = self._read_bytes().decode("utf-8")
        self.assertTrue(result.startswith(PREFIX))
        self.assertTrue(result.endswith(SUFFIX))

    def test_replace_block_is_noop_when_block_already_matches(self):
        self._write(PREFIX + OLD_MIDDLE + SUFFIX)
        before = self._read_bytes()

        self.writer.replace_block(self.path, OLD_MIDDLE)

        self.assertEqual(self._read_bytes(), before)

    def test_replace_block_with_marker_like_text_inside_block(self):
        """Documents the chosen marker-matching rule (see module docstring): the end marker is
        the RIGHTMOST `<!-- laws:end -->` line in the document. A `block` that itself quotes
        marker-look-alike text is written completely verbatim, and a subsequent `check` against
        that same block must still see zero diff — proving the extraction did not mistake the
        embedded text for the true end marker.
        """
        self._write(PREFIX + OLD_MIDDLE + SUFFIX)
        tricky_block = (
            "Some prose quoting the marker for illustration:\n"
            + END_MARKER
            + "\n"
            "More prose after the quoted marker.\n"
        )

        self.writer.replace_block(self.path, tricky_block)

        result = self._read_bytes().decode("utf-8")
        self.assertEqual(result, PREFIX + tricky_block + SUFFIX)

        zero_diff, diff = self.writer.check(self.path, tricky_block)
        self.assertIs(zero_diff, True)
        self.assertFalse(diff)

    def test_begin_marker_matched_by_prefix_only(self):
        """The begin marker is matched by its `<!-- laws:begin` PREFIX; trailing comment text
        after the prefix is not load-bearing."""
        minimal_begin = "<!-- laws:begin -->"
        full = (
            "Prose above.\n"
            "\n"
            + minimal_begin
            + "\n"
            + OLD_MIDDLE
            + END_MARKER
            + "\n"
            "\n"
            "Prose below.\n"
        )
        self._write(full)

        zero_diff, _diff = self.writer.check(self.path, OLD_MIDDLE)
        self.assertIs(zero_diff, True)

        self.writer.replace_block(self.path, "swapped content\n")

        result = self._read_bytes().decode("utf-8")
        self.assertIn(minimal_begin, result)
        self.assertIn("swapped content\n", result)
        self.assertIn("Prose below.\n", result)

    # -- 5. missing/misordered markers raise — negative controls -------------

    def test_replace_block_raises_when_neither_marker_present(self):
        full = "Just prose.\nNo markers here at all.\n"
        self._write(full)
        before = self._read_bytes()

        with self.assertRaises(ValueError):
            self.writer.replace_block(self.path, "content\n")

        self.assertEqual(self._read_bytes(), before)

    def test_replace_block_raises_when_only_begin_marker_present(self):
        full = "Prose.\n" + BEGIN_MARKER + "\nBlock without a matching end.\n"
        self._write(full)
        before = self._read_bytes()

        with self.assertRaises(ValueError):
            self.writer.replace_block(self.path, "content\n")

        self.assertEqual(self._read_bytes(), before)

    def test_replace_block_raises_when_only_end_marker_present(self):
        full = "Prose.\n" + END_MARKER + "\nMore prose, no begin marker.\n"
        self._write(full)
        before = self._read_bytes()

        with self.assertRaises(ValueError):
            self.writer.replace_block(self.path, "content\n")

        self.assertEqual(self._read_bytes(), before)

    def test_replace_block_raises_when_markers_are_in_wrong_order(self):
        full = (
            "Prose.\n"
            + END_MARKER
            + "\nMiddle prose.\n"
            + BEGIN_MARKER
            + "\nTrailing.\n"
        )
        self._write(full)
        before = self._read_bytes()

        with self.assertRaises(ValueError):
            self.writer.replace_block(self.path, "content\n")

        self.assertEqual(self._read_bytes(), before)


# ---------------------------------------------------------------------------
# per-adapter subclasses — the only place a future node needs to touch
# ---------------------------------------------------------------------------

class InMemoryTargetWriterContractTests(TargetWriterContract, unittest.TestCase):
    """The port's own reference implementation, shipped with port/target-writer (P2.3).

    graph-development.md §4: "the port task ships its own fake so consumers can proceed."
    It is what lets this suite be green at the port node, before `adapter/claude-md-target`
    exists, without the fail-open of collecting zero tests.
    """

    def make_writer(self):
        return InMemoryTargetWriter()


# adapter/claude-md-target adds its subclass here when it lands -- one small edit, no assertion
# changes, inheriting all of TargetWriterContract unchanged. Do not add the import or subclass
# until `law.adapters.claude_md_target` actually exists: an import of a module that does not
# exist yet would fail this whole file on collection and take the port's own (already-passing)
# reference-implementation tests down with it.
#
#   adapter/claude-md-target:
#       from law.adapters.claude_md_target import ClaudeMdTargetWriter
#
#       class ClaudeMdTargetContractTests(TargetWriterContract, unittest.TestCase):
#           def make_writer(self):
#               return ClaudeMdTargetWriter()


from law.adapters.claude_md_target import ClaudeMdTargetWriter  # noqa: E402


class ClaudeMdTargetContractTests(TargetWriterContract, unittest.TestCase):
    """adapter/claude-md-target (P2.6): the .claude/CLAUDE.md marker block."""

    def make_writer(self):
        return ClaudeMdTargetWriter()


if __name__ == "__main__":
    unittest.main()
