"""law.ports.target_writer — the outbound target-writer port (SPEC D15 / P2.4).

Defines the `TargetWriter` Protocol every "compile a laws block into a real target document"
adapter implements (e.g. a future `ClaudeMdTargetWriter`, per the shared contract in
`tests/law/unit/test_port_target_writer.py`), the marker constants that delimit the managed
block, and `InMemoryTargetWriter` — the port's own fake, shipped so downstream consumers and the
shared contract suite can proceed before any adapter exists (`graph-development.md` section 4).

Ports are not the pure domain (`law.core`): stdlib modules the domain forbids (`os`, `difflib`)
are fine here. Despite its name, `InMemoryTargetWriter` performs real file I/O: every method
discovers its target purely from the `path` argument it is handed, holding no additional
in-process state, mirroring `InMemoryRecordStore`'s precedent (`law.ports.record_store`).

Marker-matching rule (frozen by the contract test — implemented exactly, not reinvented here):

  - Begin: the FIRST line whose stripped text starts with the literal prefix `<!-- laws:begin`.
    Trailing comment text after the prefix is not load-bearing.
  - End: the LAST line in the whole file that exactly equals `<!-- laws:end -->` (after
    stripping), provided it appears strictly after the located begin line. Taking the
    rightmost match is deliberate: it lets a `block` that itself quotes a marker survive a
    later read without the embedded copy being mistaken for the structural end.
  - Violation (missing either marker, or the end marker at/before the begin marker) raises
    `ValueError` and leaves the file untouched — every write happens only after both markers are
    located, so a raise necessarily precedes any `open(..., "w")` call.
"""

import difflib
from typing import Protocol, Tuple

# The em dash in BEGIN_MARKER is deliberate — it is the canonical marker `claudart-law.sh compile`
# writes. The begin-matching rule below only requires the `<!-- laws:begin` prefix, so a bare
# `<!-- laws:begin -->` line (no trailing comment) matches equally.
BEGIN_MARKER = "<!-- laws:begin — generated by claudart-law.sh compile; edit frontmatter, not this block -->"
END_MARKER = "<!-- laws:end -->"

_BEGIN_PREFIX = "<!-- laws:begin"


class TargetWriter(Protocol):
    """The outbound target-writer port. An interface declaration only — no behaviour here."""

    def read(self, path: str) -> str:
        ...

    def check(self, path: str, block: str) -> Tuple[bool, str]:
        ...

    def replace_block(self, path: str, block: str) -> None:
        ...


def _locate_markers(lines):
    """Return `(begin_idx, end_idx)` into `lines` (from `str.splitlines(keepends=True)`).

    Raises `ValueError` when the begin marker is missing, the end marker is missing, or the end
    marker does not appear strictly after the begin marker. Called before any write, so every
    raise happens with zero bytes written.
    """
    begin_idx = None
    for i, line in enumerate(lines):
        if line.strip().startswith(_BEGIN_PREFIX):
            begin_idx = i
            break
    if begin_idx is None:
        raise ValueError("no `%s` marker found" % _BEGIN_PREFIX)

    end_idx = None
    for i in range(len(lines) - 1, -1, -1):
        if lines[i].strip() == END_MARKER:
            end_idx = i
            break
    if end_idx is None:
        raise ValueError("no `%s` marker found" % END_MARKER)

    if end_idx <= begin_idx:
        raise ValueError(
            "`%s` marker must appear strictly after `%s`" % (END_MARKER, _BEGIN_PREFIX)
        )

    return begin_idx, end_idx


class InMemoryTargetWriter:
    """The target-writer port's own fake, constructible with no arguments.

    Despite the name it performs real file I/O; every method discovers its target purely from
    the `path` it is handed, per the shared contract's docstring. The contract's own assertions
    read results back through direct filesystem checks (raw byte reads), so the only
    implementation that can satisfy it genuinely is one that performs the real filesystem
    operations the contract describes.
    """

    def read(self, path):
        with open(path, "r", encoding="utf-8", newline="") as handle:
            return handle.read()

    def check(self, path, block):
        text = self.read(path)
        lines = text.splitlines(keepends=True)
        begin_idx, end_idx = _locate_markers(lines)
        current = "".join(lines[begin_idx + 1 : end_idx])

        if current == block:
            return True, ""

        diff_lines = difflib.unified_diff(
            current.splitlines(keepends=True),
            block.splitlines(keepends=True),
            fromfile="current",
            tofile="block",
        )
        return False, "".join(diff_lines)

    def replace_block(self, path, block):
        text = self.read(path)
        lines = text.splitlines(keepends=True)
        begin_idx, end_idx = _locate_markers(lines)

        prefix = "".join(lines[: begin_idx + 1])
        suffix = "".join(lines[end_idx:])
        new_text = prefix + block + suffix

        with open(path, "w", encoding="utf-8", newline="") as handle:
            handle.write(new_text)
