"""graph.adapters.plan_writer — render an audit plan to disk under `--out` (D40).

Two files, both in graph-format so `claudart-graph lint --dir <out>` reads them:

  architecture.yaml  the extractor's manifest text, `architecture.budget` pinned to the MEASURED
                     violation count (audit measures the tree's real debt and ratchets from there).
  refactor-plan.md   a ROADMAP whose nodes fix each violation test-first. `lint`/`spec-run` read a
                     ROADMAP.md or ROADMAP.sample.md, so copy this file to one of those names to run.

This module writes ONLY under `out_dir`; it never touches the audited tree.
"""

import os
import re

_BUDGET_RE = re.compile(r"^(?P<lead>\s*budget:\s*)\d+\s*$", re.MULTILINE)


def _budgeted(manifest_text, count):
    """Return `manifest_text` with `architecture.budget` set to `count`."""
    text, n = _BUDGET_RE.subn(lambda m: "%s%d" % (m.group("lead"), count), manifest_text, count=1)
    if n:
        return text
    if not text.endswith("\n"):
        text += "\n"
    return text + "architecture:\n  budget: %d\n" % count


def _render_plan(project, items):
    lines = [
        "# Refactor plan - %s" % project,
        "",
        "graph-format: 1",
        "",
        "Generated by `claudart-graph audit`. Each forbidden import is repaired test-first: a test",
        "node proves the fix, the behaviour node requires it (red before green, D18). `verify:` runs",
        "the drift gate, which is green only when the measured debt is back at the pinned budget.",
        "",
        "## Phase 1 - Repair every forbidden dependency, test-first",
        "",
    ]
    for it in items:
        lines.append("- [ ] %s %s (verify: %s)" % (it.task, it.title, it.verify))
        lines.append("      node: %s | kind: %s" % (it.node, it.kind))
        for dep, etype in it.requires:
            lines.append("      requires: %s (%s)" % (dep, etype))
        if it.proves:
            lines.append("      proves: %s" % it.proves)
        if it.paths:
            lines.append("      paths: %s" % ", ".join(it.paths))
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def write_plan(out_dir, manifest_text, count, items, project):
    """Write architecture.yaml + refactor-plan.md under `out_dir`. Returns the two paths written."""
    os.makedirs(out_dir, exist_ok=True)
    mpath = os.path.join(out_dir, "architecture.yaml")
    ppath = os.path.join(out_dir, "refactor-plan.md")
    with open(mpath, "w", encoding="utf-8") as fh:
        fh.write(_budgeted(manifest_text, count))
    with open(ppath, "w", encoding="utf-8") as fh:
        fh.write(_render_plan(project, items))
    return mpath, ppath
